### ISSUE TITLE
formatlist is unknown

### ISSUE THREAD

**Issue by matti** [wata727/tflint#160] opened 2017-11-16 13:16 UTC
```
Evaluation error: 1:83: unknown function called: formatlist in e.tf:6
```

**Comment by wata727** [comment] 2017-11-25 07:56
Thanks @matti 
This problem is caused by TFLint not supporting all Terraform syntax. Generally, unsupported syntaxes are ignored, but errors occurred when using them as attributes of modules.

This is a difficult problem. As a workaround, I plan to implement a feature that can ignore the module causing the error.

**Comment by wata727** [comment] 2017-11-25 12:02
Oh no, I was the misunderstanding. Originally it will not occur an error, just calling `formatlist` should be ignored.

Can you show me the `e.tf` for further investigation?

**Comment by wata727** [comment] 2019-05-25 17:26
Close this issue because the current implementation has changed significantly. Please try the latest version again. If you still have problems, please open a new issue instead of reopening.

**Closed by wata727** 2019-05-25 17:26 UTC
