### ISSUE TITLE
Tflint is detecting errors with respect to referencing's in terraform code

### ISSUE THREAD

**Issue by sandeepsharmadevops** [wata727/tflint#120] opened 2017-07-01 12:46 UTC
Hi,

I am using your tool for validating our terraform code which cannot be captured by terraform plan to avoid any issues while running the terraform apply.  but while using it i am facing some issues in terms of validating, before jumping onto the issues, let me give you the context about our terraform code.

Context:
I am using two types of referencing in my terraform code:
1. module output referencing [referencing output values from one module into other
eg: module.apptier_1_route_table.route_table_id
2. referencing values from terraform remote state files [i am managing the multiple terraform state files and referencing values from these terraform remote state files at other places]
eg: data.terraform_remote_state.nat_gw.nat_gw_ids_list

Issue:
While validating our terraform code via tflint, it is giving errors with respect to these types of referencing s, sample of those errors are given below
---------------------------------------------------------------------------------------------------------------
../../../modules/route_tables/rt_routes/igw/main.tf
	ERROR:11 "${data.terraform_remote_state.vpc.vpc_info["main_route_table_id"]}" is invalid route table ID.
	ERROR:13 "${data.terraform_remote_state.vpc.vpc_info["igw_id"]}" is invalid internet gateway ID.
../../../modules/route_tables/rt_routes/nat_gw/main.tf
	ERROR:11 "${module.apptier_1_route_table.route_table_id}" is invalid route table ID.
	ERROR:11 "${module.apptier_2_route_table.route_table_id}" is invalid route table ID.
	ERROR:13 "${data.terraform_remote_state.nat_gw.nat_gw_ids_list[0]}" is invalid NAT gateway ID.
	ERROR:13 "${data.terraform_remote_state.nat_gw.nat_gw_ids_list[1]}" is invalid NAT gateway ID. 

---------------------------------------------------------------------------------------------------------------
But there is one more catch in this, i am maintaining the terraform code in different directories and running tflint at each location to validate, terraform code at all locations having this referencing code, but tflint is not detecting these referencing's as an errors at all locations (our terraform code is working fine in terms provisioning aws resources with these types of referencing's).

Queries:
1. How this can happen that tflint is detecting these referencing's as an errors at some locations?
2. What configuration or parameter should be passed while running tflint so that it can ignore these errors (i mean does not show)?
3. How to ignore notices as well?
4. We only want to get the validation error with respect to actual's like ami id and instance type is not valid?

Let me know if anything else is required in same from my side.

Thx.

**Comment by wata727** [comment] 2017-07-01 14:19
Hi @awscodedeploy, thanks for using TFLint.

I answer your questions:

> How this can happen that tflint is detecting these referencing's as an errors at some locations?

TFLint interpolates only variables (e.g. `${var.instance_type}`). So, module attributes (e.g. `${module.apptier_2_route_table.route_table_id}`), data attributes (e.g. `${data.terraform_remote_state.nat_gw.nat_gw_ids_list[0}`) are not interpolated when it detecting templates.
As a result, values not interpolated are treated as raw values and TFLint detects it as an invalid ID.

> What configuration or parameter should be passed while running tflint so that it can ignore these errors (i mean does not show)?

Unfortunately, It is not possible to ignore issues in cases where interpolation is impossible. I feel this behavior as a problem and I'm going to fix it so that you can ignore the issues in such a case.

> How to ignore notices as well?

You can ignore issues by specifying module's source or rule name. Please check the [README](https://github.com/wata727/tflint#configuration).

> We only want to get the validation error with respect to actual's like ami id and instance type is not valid?

Do you mean you want to enable only deep check rules? In that case, please set to ignore other than deep check rules. A list of rules is [here](https://github.com/wata727/tflint/tree/master/docs).

**Comment by awscodedeploy** [comment] 2017-07-01 16:08
Thanks a lot for your prompt , Please update me once your are done with second point.

**Comment by awscodedeploy** [comment] 2017-07-12 16:00
Hi,

Any update on Query 1, i can see that there is latest tflint is available with Override module support, does this helps us in our first query?

Thx

**Comment by wata727** [comment] 2017-07-13 14:22
Sorry, there is no relationship between this problem and override module support...

**Comment by wata727** [comment] 2017-07-15 07:40
@awscodedeploy I'm investigating about this issue now, but I can not reproduce it... Also, I realized that I was misunderstanding in https://github.com/wata727/tflint/issues/120#issuecomment-312434651

When there is a value which can not be interpolated (eg. `${module.apptier_2_route_table.route_table_id}`), TFLint ignores rules on that value. So, this issue should not occur.

Can you show me a template that actually causes this issue?

**Comment by wata727** [comment] 2019-05-25 17:17
Close this issue because the current implementation has changed significantly. Please try the latest version again. If you still have problems, please open a new issue instead of reopening.

**Closed by wata727** 2019-05-25 17:17 UTC
