### ISSUE TITLE
invalid characters in heredoc anchor

### ISSUE THREAD

**Issue by venkatraj-icp** [wata727/tflint#192] opened 2018-05-10 02:07 UTC
Hi,
Iam new to Terraform 
Getting error while deploy : invalid characters in heredoc anchor (line 6:14) (data = <<EOF)
Syntax:
======================================================
resource "camc_bootstrap" "Hostname_chef_bootstrap_comp" {
	name = "Hostname_chef_bootstrap_comp"
	camc_endpoint = "http://${var.ibm_pm_service}:5443/v1/bootstrap/"  
	access_token = "${var.ibm_pm_access_token}"
	trace = "true"
	data = <<EOF 
	{
		"os_admin_user" = "${var.os_admin_user}",
		"stack_id" = "${var.ibm_stack_id}",
		"environment_name" = "_default",
		"host_ip" = "${var.ipv4_address}",
		"node_name" = "${var.name}",
		"node_attributes" = {
			"ibm_internal" = {
				"stack_id" = "${var.ibm_stack_id}",
				"stack_name" = "${var.name}",
				"vault" = {
					"item" = "secrets",
					"name" = "${var.ibm_stack_id}"
				}
			}
		}
	}
	EOF
}
---------------------------------------------------------------------------------------------------------------
Kindly guide me to fix this issue
Thanks

**Comment by wata727** [comment] 2018-05-18 12:54
Umm... I cannot reproduce it...
Please tell me the following:

1. Do `terraform plan` work correctly for that template?
2. What is the version of Terraform and TFLint?
3. What a command does the same error occur? (e.g. `tflint your_template.tf`)

**Comment by wata727** [comment] 2019-05-25 17:36
Close this issue because the current implementation has changed significantly. Please try the latest version again. If you still have problems, please open a new issue instead of reopening.

**Closed by wata727** 2019-05-25 17:36 UTC
