### ISSUE TITLE
Tflint doesn't seem to be reading the tfvars file

### ISSUE THREAD

**Issue by Puneeth-n** [wata727/tflint#207] opened 2018-06-25 14:20 UTC
```
➜  services git:(master) ✗ tflint --version
TFLint version 0.7.0
```

```
➜  services git:(master) ✗ cat .tflint.hcl
config {
  terraform_version = "0.10.8"
  deep_check = true
}
```

```
➜  services git:(master) ✗ tflint --var-file=./config/alpha.tfvars --debug
DEBUG:/loader.go:121 [INFO] Load environment...
DEBUG:/loader.go:129 [ERROR] open .terraform/environment: no such file or directory
DEBUG:/loader.go:132 [INFO] Load tfstate...
DEBUG:/loader.go:136 [ERROR] stat terraform.tfstate: no such file or directory
DEBUG:/loader.go:139 [ERROR] stat .terraform/terraform.tfstate: no such file or directory
DEBUG:/loader.go:162 [INFO] Load tfvars...
DEBUG:/loader.go:165 [INFO] Load `terraform.tfvars`
DEBUG:/loader.go:167 [ERROR] stat terraform.tfvars: no such file or directory
DEBUG:/loader.go:165 [INFO] Load `./config/alpha.tfvars`
DEBUG:/loader.go:192 [INFO] Load HCL file: `./config/alpha.tfvars`
DEBUG:/loader.go:192 [INFO] Load HCL file: `apig_currency_rates.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `apig_currency_rates.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `apig_db_callback.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `apig_db_callback.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `apig_googlemaps.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `apig_googlemaps.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `apig_zendesk_logging.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `apig_zendesk_logging.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `booking_sfn.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `booking_sfn.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `cognito.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `cognito.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `ct-backend.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `ct-backend.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `ct_backend_service_addon.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `ct_backend_service_addon.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `ct_backend_service_base.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `ct_backend_service_base.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `ct_backend_service_booking.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `ct_backend_service_booking.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `ct_backend_service_booking_varnish.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `ct_backend_service_booking_varnish.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `ct_backend_service_checkout.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `ct_backend_service_checkout.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `ct_backend_service_cockpit.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `ct_backend_service_cockpit.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `ct_backend_service_cockpit_logging.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `ct_backend_service_cockpit_logging.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `ct_backend_service_crm.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `ct_backend_service_crm.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `ct_backend_service_document_storage.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `ct_backend_service_document_storage.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `ct_backend_service_duckling.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `ct_backend_service_duckling.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `ct_backend_service_https_redirect.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `ct_backend_service_https_redirect.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `ct_backend_service_logstash.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `ct_backend_service_logstash.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `ct_backend_service_meta_data.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `ct_backend_service_meta_data.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `ct_backend_service_my_comtravo.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `ct_backend_service_my_comtravo.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `ct_backend_service_nlp.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `ct_backend_service_nlp.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `ct_backend_service_payment.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `ct_backend_service_payment.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `ct_backend_service_pdf_generator.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `ct_backend_service_pdf_generator.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `ct_backend_service_revalidation.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `ct_backend_service_revalidation.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `ct_backend_service_search.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `ct_backend_service_search.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `ct_backend_service_ticket.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `ct_backend_service_ticket.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `ecs_manager_sfn.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `ecs_manager_sfn.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `firehose.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `firehose.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `lambdas.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `lambdas.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `outputs.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `outputs.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `production.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `production.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `provisioner.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `provisioner.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `remote_state.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `remote_state.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `staging.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `staging.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `variables.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `variables.tf`
DEBUG:/loader.go:192 [INFO] Load HCL file: `vpc.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `vpc.tf`
Evaluation error: 1:3: unknown variable accessed: var.replication_factor in ct_backend_service_duckling.tf:70
```

alpha.tfvars
```
ct_environment_name = "alpha"
replication_factor = 1
ct_account_id = "1234567890"
ct_vpc_cidr = "10.1.0.0/16"
```

**Comment by wata727** [comment] 2018-06-27 13:57
Hi @Puneeth-n,

I confirmed that the same problem will be reproduced in the following example.

**template.tf**

```hcl
module "ecs_on_spotfleet" {
  source = "github.com/wata727/tf_aws_ecs_on_spotfleet.git"

  vpc         = "vpc-12345678"
  subnets     = ["subnet-12345678", "subnet-87654321"]
  spot_prices = ["0.067000", "0.006700"]
  key_name    = "${var.foo}"
}
```

**config.tfvars**

```
foo = "test-app"
```

```
$ tflint --var-file=config.tfvars
Evaluation error: 1:3: unknown variable accessed: var.foo in template.tf:7
```

But, it's an intended behavior because the following example doesn't work when run `terraform plan`.

```
$ terraform plan

Error: module 'ecs_on_spotfleet': unknown variable referenced: 'foo'; define it with a 'variable' block
```

Is this the same problem you are facing?

**Comment by Puneeth-n** [comment] 2018-06-28 13:53
@wata727 yes

**Comment by ketzacoatl** [comment] 2018-07-04 15:31
I can also confirm running into this:

```
ᐅ tflint                                                         
Evaluation error: 1:3: unknown variable accessed: var.vpc_cidr in main.tf:46
```

`vpc_cidr` definitely exists, is used elsewhere, and `tf plan`/etc works without issue, it's just `tflint` throwing an error on this variable.

**Comment by wata727** [comment] 2019-05-25 17:47
Close this issue because the current implementation has changed significantly. Please try the latest version again. If you still have problems, please open a new issue instead of reopening.

**Closed by wata727** 2019-05-25 17:47 UTC
